# Generated by Django 2.0.6 on 2019-03-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='封面图')),
                ('article', models.TextField(verbose_name='文章内容')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('read_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('praise_count', models.IntegerField(default=0, verbose_name='喜欢次数')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('email', models.CharField(max_length=50, verbose_name='用户邮箱')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户网站')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='站长回复')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='链接名')),
                ('url', models.URLField(verbose_name='友情链接')),
            ],
        ),
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='阶段')),
                ('article', models.TextField(verbose_name='个人简介')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comment_content',
            field=models.ManyToManyField(blank=True, to='blog.Comment', verbose_name='评论信息'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
    ]
