# Generated by Django 2.0.6 on 2019-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
        migrations.AddField(
            model_name='tag',
            name='major',
            field=models.BooleanField(default=False, verbose_name='是否是主标签'),
        ),
    ]
