# Generated by Django 2.0.6 on 2019-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190324_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.IntegerField(default=0, verbose_name='内层被回复人ID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='被回复人昵称'),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_id',
            field=models.IntegerField(default=0, verbose_name='外层被回复人ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论/回复内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=50, verbose_name='访客邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论/回复时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=20, verbose_name='访客昵称'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='访客网站'),
        ),
    ]
